### ISSUE TITLE
Bug: editor never stops loading

### ISSUE THREAD

**Issue by StoreMax** [SanderRonde/CustomRightClickMenu#1]
![screencap 1](https://cloud.githubusercontent.com/assets/19758662/15804530/417b5a1a-2b0c-11e6-92d2-130a340b7b15.png)

never stops loading

[settings (1).txt](https://github.com/SanderRonde/CustomRightClickMenu/files/299265/settings.1.txt)

**Comment by SanderRonde** [comment]
Thanks for the report, the fix should be live in about an hour.
