### ISSUE TITLE
GM_xmlhttpRequest not working 

### ISSUE THREAD

**Issue by bumaociyuan** [SanderRonde/CustomRightClickMenu#11]
My script worked well couple weeks ago.
But today I got this error
```
Uncaught TypeError: Cannot read property '_setupRequestEvent' of undefined
```

on `GM_xmlhttpRequest` sending a request

**Comment by SanderRonde** [comment]
Hey I found the source of the problem and just wanted to say that a fix should be live in around half an hour, which chrome will probably distribute to you in the coming 12-ish hours.

**Comment by SanderRonde** [comment]
Coming back to what I just said, google decided to investigate this update (it's a random-ish thing they do) so it can take anywhere from 1 to 7 days to months depending on how fast it goes (but probably a couple of days). You'll know it's live when you're running 2.0.13, or when your script works again of course.

**Comment by bumaociyuan** [comment]
@SanderRonde Thank you for reply
