### ISSUE TITLE
Empty Links in a node are still being invoked

### ISSUE THREAD

**Issue by ToastyStoemp** [SanderRonde/CustomRightClickMenu#16]
Not sure if this is something anyone would really want, but opening blank pages is rather useless?

**Comment by SanderRonde** [comment]
I agree that it's rather useless but if #15 is fixed there's no need to have blank URLs anymore. I feel like it would be even more confusing if links are just not opened at all, as opening a faulty URL allows the user to more easily spot it being faulty than not opening it at all and displaying an error message somewhere in the console.
