### ISSUE TITLE
Is this extension support url like file:///

### ISSUE THREAD

**Issue by ma-tongji** [SanderRonde/CustomRightClickMenu#19]
Hi,

I'm using the extension and it works well for images on internet, but there seems no effect on local images? I need the file path for local images like "file:///path/to/image.jpg" #

**Comment by SanderRonde** [comment]
Do you mean being able to run on file:// urls or being able to open local urls in a new tab? The first one isn't possible and i'm fairly sure the second one isn't either but if the second one is what you meant then i will take a look at it tomorrow to see if it might be possible.

**Comment by ma-tongji** [comment]
The 1st one... I'm searching images with some website and I want to run the extension on file:// urls. Is this limited by chrome so extensions cannot run on local file:// urls?

**Comment by SanderRonde** [comment]
Well it turns out that I was wrong, it is actually possible to do so. To enable it go to chrome://extensions and enable the "allow access to file URLs" checkmark below the extension. That should allow scripts etc to run on file:// urls as well.

**Comment by ma-tongji** [comment]
Wow, thanks. I'm fool. The option is obviously there but I missed that several times.
