### ISSUE TITLE
Question: Possible to use the context menu to execute a keyboard shortcut?

### ISSUE THREAD

**Issue by PKoelewijn** [SanderRonde/CustomRightClickMenu#20]
Is it possible to use the context menu to execute a keyboard shortcut? Because I'm using an external (VoIP) application where I can select a phone number and then start calling through pushing a keyboard shortcut. I'd like to map this keyboard shortcut to the context menu for ease of access for myself and others.

**Comment by SanderRonde** [comment]
What you could do is to create an AutoHotkey script that will press the keyboard shortcut for you. You can then use [this guide](https://github.com/SanderRonde/CustomRightClickMenu/wiki/Opening-a-desktop-program) to open the AutoHotkey program with a link. I'm guessing there is some way to run scripts from the command line, which you can then use to pass the script you want to run to AutoHotkey. 

There's no way to do it natively in chrome. Chrome extensions do not have the ability to simulate key presses so the only way to do it is to run another program which can do it instead.

If you need any help setting up the AutoHotkey linking please let me know and I'll try if I can figure it out.
