### ISSUE TITLE
Options fail to load - Firefox 61.0b11

### ISSUE THREAD

**Issue by imcraymond** [SanderRonde/CustomRightClickMenu#24]
Hitting F12 shows two errors:

TypeError: menuBrowserAPI is undefined ... options.js:162:9592
TypeError: browserAPI is undefined ... options.ja:154:1734

**Comment by SanderRonde** [comment]
Hey thank you very much for reporting the issue. I'm pretty sure I've found the problem and fixed it. A patch will be released pretty soon in which it will be fixed.
