### ISSUE TITLE
Question: How do I assign a shortcut to a menu item?

### ISSUE THREAD

**Issue by catbehemoth** [SanderRonde/CustomRightClickMenu#26]
How do I assign a shortcut to a menu item?
Sorry, it doesn't seem to work through chrome://extensions/shortcuts or maybe it's not even for this?
Thanks

**Comment by SanderRonde** [comment]
The first step is to create a generic keyboard shortcut in chrome://extensions/shortcuts. I think this is the step you've already done. Simply create a shortcut to any of the "CRM Keyboard Shortcut number X" fields. The number at the end doesn't matter.

The second step is listening for this keypress and responding to it. You can do this by creating a script item, clicking the "background" tab and adding the following code:

```javascript
crmAPI.background.addKeyboardListener('Ctrl+Shift+I', () => {
	//Some callback
});
```

Where 'Ctrl+Shift+I' is replaced by the keyboard shortcut you want to register.
At this point you can do two things. 

The first option is that you run all the logic in the backgroundpage (in the callback), which would be handy if you're creating a counter of howmany times you've pressed the keyboard shortcut or something along those lines.

The second option is to run a script on the page you're currently on, which is probably what you'll want to do. You can do this by putting the following code in the callback:

```javascript
crmAPI.chrome('tabs.query', function (tabs) {
	crmAPI.background.runSelf({
		tabId: tabs[0].id
	});
});
```

This will then run the regular script (the one you see if you switch from the background to the main tab) on the currently selected page.

I hope this answers your question.

**Comment by catbehemoth** [comment]
thank you for taking time to reply to me.
my idea I had, I'll explain to on google search example. I want to achieve: I select a word on a page, press ctrl+shift+1 and it runs the script of the menu item. Therefore I went with your second option, but it doesn't work, most likely due to my lack of scripting knowledge.
Can you tell what am i doing wrong?
I associated a shortcut in chrome://extensions/shortcuts as ctrl+shift+1  (CRM Keyboard Shortcut number 1)
then I added a new menu items from your "Commonly Used Search Engines" list, so the code of main tab looks like this:
`var query;
var url = "https://www.google.com/search?q=%s";
if (crmAPI.getSelection()) {
	query = crmAPI.getSelection();
} else {
	query = window.prompt('Please enter a search query');
}
if (query) {
	window.open(url.replace(/%s/g,query), '_blank');
}`

and background tap looks like this:
`crmAPI.background.addKeyboardListener('Ctrl+Shift+1', () => {
});
crmAPI.chrome('tabs.query', function (tabs) {
	crmAPI.background.runSelf({
		tabId: tabs[0].id
	});
});`

Thank you for your help.

**Comment by SanderRonde** [comment]
The first thing it could be is that the code that should run the script is outside of the listener. This means that instead of running when you press the shortcut, it runs when the background script is first started.
So instead of this code:

```javascript
crmAPI.background.addKeyboardListener('Ctrl+Shift+1', () => { 
}); 
crmAPI.chrome('tabs.query', function (tabs) { 
    crmAPI.background.runSelf({ tabId: tabs[0].id }); });
```
You should use this code:

```javascript
crmAPI.background.addKeyboardListener('Ctrl+Shift+1', () => {
    crmAPI.chrome('tabs.query', function (tabs) { 
        crmAPI.background.runSelf({ tabId: tabs[0].id }); 
    });
});
```

**Comment by catbehemoth** [comment]
sorry, tried it still doesn't work.... if I have more times I'll send you screenshot, but i have done everything as you said.

**Comment by SanderRonde** [comment]
Can you export your settings and paste them here? Then I can try it myself and see where it stops working.

**Comment by SanderRonde** [comment]
Closing this issue for now as there's been no update in ~2 weeks
