### ISSUE TITLE
Question:  How to add new right-click entry on the same level as "Quick Menu"?

### ISSUE THREAD

**Issue by noxcovenant** [SanderRonde/CustomRightClickMenu#28]

**Comment by noxcovenant** [comment]
I've tried adding shortcuts to the existing Quick Menu, but it's starting to get really convoluted going through so many side-menus to get my link. I'm curious if I can just make a new right-click entry on the same level as "Quick Menu".

By the way, thanks for this add-on. :)

**Comment by SanderRonde** [comment]
Hey, if I'm understanding it correctly you mean a menu on the same level as the copy, paste and all those types of buttons. Unfortunately that's not possible. The API only allows a single per-extension entry.

**Comment by noxcovenant** [comment]
Hello,

That's exactly my question and that's a bummer. It seems like Firefox's move to the new API has crippled menu customization the most 

Thanks for the quick reply though and all your hard work. I may need to wait a bit before I can
