### ISSUE TITLE
Feature request: Add icons to menu items if possible 

### ISSUE THREAD

**Issue by yaka996** [SanderRonde/CustomRightClickMenu#34]
Hello,
Thank you for this useful extension.
Is would be nice if there is a possibility to add icons to the menu items.
Thanks

**Comment by SanderRonde** [comment]
While this would indeed be a great feature, this is not possible for regular menus (as per the docs: https://developer.chrome.com/apps/contextMenus#method-create) but it's only possible for the root item. It also takes the extension's icon for the root node's icon so there's no ability to customize it.
