### ISSUE TITLE
How do you delete a menu item?

### ISSUE THREAD

**Issue by gitaarik** [SanderRonde/CustomRightClickMenu#37]
Hey man,

Nice project, very handy!

I've got an annoying little problem. I cannot find out how to delete a menu item. How can you delete a menu item?

Thanks brother

![Screen Shot 2019-09-15 at 22 22 07](https://user-images.githubusercontent.com/2470302/64927154-4aa1d000-d807-11e9-8cce-73e6448527c4.png)

**Comment by SanderRonde** [comment]
You'll want to click the "select" button (see image)

![](https://i.imgur.com/AtTxX6N.png)

Then you can click the item(s) you want to remove to select them and then "remove selected".

I hope this helps. If it doesn't please let me know, and if it does be sure to close the issue.

**Comment by gitaarik** [comment]
Oh, haha, I didn't expect to find it there. Thank you!

**Comment by Jon8RFC** [comment]
Thank you for explaining this.  This was very difficult to determine.
