### ISSUE TITLE
About right click and get anchor href send to context menu variable.

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#4]
Hello I'm fresh to use this Chrome extension.

I try to write script for some function I want to specify on a site search query.

```
var query = window.getSelection();
if (query != '') {
var url = "http://sci.abc/??check=true&request=%s";
window.open(url.replace(/%s/g,query), '_blank');
}
else {
window.open("http://sci.abc/", '_blank');
}
```

But I don't know how to detect the href of the anchor link if I try to select the text with link inside. I want to send the href to `query` if the mouse is over or right click on the text with `<a>`

Could you help? Thanks!

**Comment by SanderRonde** [comment]
Hey what version of the extension are you using? The old one or the new one? (the new one has a big orange banner at the top of the options page)

**Comment by pendave** [comment]
I use 
Custom Right-Click Menu 2.0.1

**Comment by SanderRonde** [comment]
Then this code should do the job for you:

```
/*execute locally*/
var query = linkurl || window.getSelection();
if (query != '') {
var url = "http://sci.abc/??check=true&request=%s";
  window.open(url.replace(/%s/g,query), '_blank');
}
else {
  window.open("http://sci.abc/", '_blank');
}
```

Include the "execute locally" part as well

**Comment by pendave** [comment]
Thanks it works, is "linkurl" an internal defined varial?

Do you have details document for this extension?

**Comment by SanderRonde** [comment]
Yeah it is, if you click on the little cogwheel next to the editor on a script type node there's some details about it. Basically the lowercase version of any parameter in the "onclick" section of [this function](https://developer.chrome.com/extensions/contextMenus#method-create) are internally defined variables.

**Comment by pendave** [comment]
Another problem as I change this but it does not work:
`var query = linkurl || window.getSelection() || window.location.href;`

That mean if I click any blank place on the page, it will get the page's location and query it as well as 
```
if (query != '') {
var url = "http://sci.abc/??check=true&request=%s";
  window.open(url.replace(/%s/g,query), '_blank');
}
```
