### ISSUE TITLE
library cant be deleted...

### ISSUE THREAD

**Issue by erikdemarco** [SanderRonde/CustomRightClickMenu#43]
when we add library and we decided to delete it. it will never gets deleted

**Comment by erikdemarco** [comment]
at first it seems to get deleted. but if you open the library menu after a wihile the library that is deleted show up again.

**Comment by SanderRonde** [comment]
Does this persist after refreshing the page? There seem to be a few bugs that only persist while the page is not reloaded.

**Comment by SanderRonde** [comment]
Closing this issue since there's no response
