### ISSUE TITLE
How can I get the textContent from the selected URL ?

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#46]
I use `console.log(crmAPI.getClickInfo());` but there's no textContent in the dict:

![image](https://user-images.githubusercontent.com/1331881/76819590-93ccee00-6843-11ea-968e-1bba1d85d424.png)

I wanna copy out the text of the link such as this twitter's autor name:
![image](https://user-images.githubusercontent.com/1331881/76819631-b232e980-6843-11ea-99a3-6a1208ffb1fe.png)

**Comment by SanderRonde** [comment]
That is the click data passed by the chrome.contextMenus API directly and it's probably not very useful for this purpose. You might have more luck using crmAPI.contextData.target and getting its innerText manually.

**Comment by pendave** [comment]
Thanks, it works well!
`const element = document.createElement('span');
element.innerText = crmAPI.contextData.target.textContent;
document.body.appendChild(element);

const snipRange = document.createRange();
snipRange.selectNode(element);
const selection = window.getSelection();
selection.removeAllRanges();
selection.addRange(snipRange);
try {
	document.execCommand('copy');
} catch(e) {
	console.log(e);
}

selection.removeAllRanges();
element.remove();`

**Comment by SanderRonde** [comment]
Good to hear, I'll close the issue then
