### ISSUE TITLE
console.log not working

### ISSUE THREAD

**Issue by alibaltschun** [SanderRonde/CustomRightClickMenu#47]
i tried create a script just call console.log("x") but its not working

**Comment by SanderRonde** [comment]
What kind of script did you make and when should it run? Could you export the extension's data from the options page so I can take a look?

**Comment by deepesh-agarwal** [comment]
Same here, the script is executed on button click with selected text.:

```
var email = crmAPI.getSelection();
console.log(email);
```

**Comment by SanderRonde** [comment]
Can you export the extension's data so I can take a look at it? Maybe I can find out what it is.

**Comment by SanderRonde** [comment]
Closing since there's been no update for quite a while
