### ISSUE TITLE
The window.getSelection() is not working for the selected text in webpage for searching.

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#5]
I test this code but the window.getSelection() is not working for the selected text in webpage for searching. How to fix it?

I check out that `/*execute locally*/` only makes `query = linkurl` works but `window.getSelection()` not.
Thanks.

```
/*execute locally*/
var query = linkurl || window.getSelection() ;
if (query != '') {
var url = "http://sci.abc/??check=true&request=%s";
  window.open(url.replace(/%s/g,query), '_blank');
}
else {
  window.open("http://sci.abc/", '_blank');
}
```

**Comment by SanderRonde** [comment]
Yes that is correct, it either gets those parameters or it executes on the page and instead gets access to the window. 

However you can use the "selectiontext" property just like you used the linkurl property and that should fix it.
