### ISSUE TITLE
get url of right clicked image

### ISSUE THREAD

**Issue by Moko0815** [SanderRonde/CustomRightClickMenu#51]
how can i get the url from a image, for example to make an alertbox with the url.
thanks.

**Comment by SanderRonde** [comment]
You should be able to get the target element with `crmAPI.contextData.target`, then you can get its source with `.src`. So `crmAPI.contextData.target.src` should get you the URL. Then you can alert it to view it with 
```js
alert(crmAPI.contextData.target.src)
```

**Comment by Moko0815** [comment]
it works
thank you for the fast answer
my script for searching pics on google with picturesearch:
```
var imgFullURL = crmAPI.contextData.target.src;
var url = "https://images.google.com/searchbyimage?hl=en&biw=1060&bih=766&gbv=2&site=search&image_url=" + imgFullURL;
window.open(url);
```

**Comment by SanderRonde** [comment]
Oh that's pretty smart actually. I'll close the issue now
