### ISSUE TITLE
Crash while configuring menu

### ISSUE THREAD

**Issue by nathgit** [SanderRonde/CustomRightClickMenu#52]
The "config page(?)" crashes while I'm trying to configure it. I managed to add one menu with 3 items, When I try to add more than that the page crashes & I have to reload the page. This has happened several times. I haven't installed it yet, & that makes me have second thoughts about installing it. On top of that it's very unclear exactly how to use it. For example how to add something to a secondary menu vs the main menu. Is that going to continue if I install it, because if so I'll be uninstalling it immediately & giving it a bad review. I don't mean to be harsh, but when I haven't even installed & I'm already seeing crashes It doesn't instill to much confidence that it won't be even worse if I install it.

**Comment by nathgit** [comment]
OS: Chrome OS 86

**Comment by SanderRonde** [comment]
Hi, how exactly are you using it without installing it? Are you using the demo or is there some fancy chrome OS feature I'm not aware of? To answer your question about the secondary menu vs main menu: There is only one menu. This menu can have submenus but there will always be one root menu. This is a restriction by chrome (and other browsers). 

I certainly agree that it's not very intuitive to use, however it's a lot of work making it very intuitive given it's got a lot of features, and unfortunately I'm quite busy at the moment so I don't have a lot of time to do so.

**Comment by nathgit** [comment]
I'm using the demo. What I mean by a second menu is I added a submenu with a couple user styles but  I want add another item to the root menu. When I try to add that second item, is when it crashes, almost every time. I fully understand it's hard to make something so full of features intuitive, but is it possible to just create a tutorial, even just a page here describing how to use it? I also worry about it crashing & somehow screwing up the standard right click menu.

**Comment by SanderRonde** [comment]
> I'm using the demo. What I mean by a second menu is I added a submenu with a couple user styles but I want add another item to the root menu. When I try to add that second item, is when it crashes, almost every time. 

Ah yeah the demo is a bit buggy. It's not really meant to be used that intensively other than testing out the UI a bit.

> I fully understand it's hard to make something so full of features intuitive, but is it possible to just create a tutorial, even just a page here describing how to use it?

Yes I should have definitely done this back when I created this extension. However at this point it's more so in maintenance mode. It's a bit of long story as to why, the full thing is in #44 but the short story is: if I upload a new version, it will likely be removed by Google along with my entire Google account. For that reason I'm a bit apprehensive about updating it. I could get it all back but it takes a few months (last time it took ~3).

>  I also worry about it crashing & somehow screwing up the standard right click menu. Is there a video somewhere of it in action?

It definitely won't crash and screw up the standard right click menu. It only occupies a single entry in the menu (similar to the copy and paste buttons only occupying one) and won't touch the others at all. In the worst case the created entry is just empty or something, in which case you can always delete the extension. Also there is no video unfortunately, there is [a wiki](https://github.com/SanderRonde/CustomRightClickMenu/wiki) with some entries in it but it's not that complete.
