### ISSUE TITLE
Stylesheets for select sites not working

### ISSUE THREAD

**Issue by nathgit** [SanderRonde/CustomRightClickMenu#53]
I went ahead & installed it & it worked until I tried to add a stylesheet for an individual site. I had 3 stylesheets, a black theme, a white theme, & a grey theme. Once I added the custom style (for duckduckgo) it only shows the black theme. I tried just deleting that entry but it didn't fix it. fortunately I had exported the config before adding the site style so I imported that & the other scripts came back.

**Comment by nathgit** [comment]
Using a chromebook version 86

**Comment by SanderRonde** [comment]
Can you maybe send me the config so I can give it a try myself?

**Comment by nathgit** [comment]
[custom_menu_bug-files.zip](https://github.com/SanderRonde/CustomRightClickMenu/files/5579921/custom_menu_bug-files.zip)
Here's a zip with the Menu config & the css files (duckduckgo & github)

**Comment by nathgit** [comment]
I got the stylesheets from:
Github Nord
http://userstyles.org/styles/191792

New DuckDuckGo - Dark Theme
http://userstyles.org/styles/101431
(using stylus)

**Comment by SanderRonde** [comment]
Looks like the themes themselves are a bit flawed. They only set some the background color but don't actually mark it as `!important` so the browser ignores it and uses the page's regular CSS. It also sets the text color for the body but of course the page itself overrides that at a lower level so it doesn't do anything. 

I would look at the styles you linked but I seem to be getting an error 504 so that makes it a bit hard.

**Comment by nathgit** [comment]
They work fine when I apply them through stylus. I exported them as moz-document format.
[userscripts.zip](https://github.com/SanderRonde/CustomRightClickMenu/files/5579965/userscripts.zip)

**Comment by SanderRonde** [comment]
Looks like the DDG dark theme one and the github one work just fine, it's just the black, white and grey theme ones that don't work and that appears to be from the CSS not working for the page.

**Comment by nathgit** [comment]
[CM_working.zip](https://github.com/SanderRonde/CustomRightClickMenu/files/5580001/CM_working.zip)
Those styles work just fine until I add the DDG & github styles. Only then do I have any problem.

**Comment by SanderRonde** [comment]
I don't think I'm understanding what is going on. So initially you have those 3 styles, then when you add the DDG and github styles (how are you adding them?) it goes wrong and you have a problem. What is the problem? Do the original 3 styles disappear from the right-click menu, do they simply not work anymore or what?

**Comment by nathgit** [comment]
The 3 work fine, then I add other 2 just like the first 3 except choosing the option to only show them on their specific sites, then when I go back to page to try it, only the black theme shows up.

**Comment by SanderRonde** [comment]
Ah okay, so of those three the black theme (guess the one named "black theme") is the only one that shows up? I'm trying to replicate it but I seem to get all of them when I try your initial `custom-menu-not_working.txt` file. Does the problem persist if you re-import your settings?

**Comment by nathgit** [comment]
The problem seems to happen as soon as I add anything beyond the first 3. I tried adding a red theme, just like the first 3 & the same thing happened.

**Comment by SanderRonde** [comment]
It looks like I can't really seem to replicate this so I can't do much to help you here. I'm sorry.
