### ISSUE TITLE
Get Selected Elements

### ISSUE THREAD

**Issue by ramtinarefkia** [SanderRonde/CustomRightClickMenu#55]
How can I retrieve selected **elements** ? _crmAPI.getSelection()_ gives the selected text & _crmAPI.contextData.target_ gives just clicked element ; what I want , is to retrieve all elements related to selected text on page
tnx

**Comment by SanderRonde** [comment]
Looks like someone has figured out a way to do this [in this stackoverflow post](https://stackoverflow.com/questions/5083682/get-selected-html-in-browser-via-javascript).

**Comment by ramtinarefkia** [comment]
Yeah that code works but in my particular case , it doesn't ; so I end up with your awesome extensions to manipulate right click menu & somehow get selected elements through it , so I'm thinking about implementing this with crmAPI rather than regular js .
can you tell me how can i get selected text line by line via _crmAPI.getSelection()_ instead ?

**Comment by ramtinarefkia** [comment]
I changed that code & now is working in my particular case , thank you anyway

**Comment by SanderRonde** [comment]
Good to hear!
