### ISSUE TITLE
Execute when visiting specified sites

### ISSUE THREAD

**Issue by Dursii** [SanderRonde/CustomRightClickMenu#56]
**Execute when visiting specified sites only runs when the config has been updated. The tab needs to already be open, then you must resave the script in question that will run on the site. This script will now function on this tab, but upon closing the tab and opening the same page, the script fails to load.**

Use case:
I'm using CRCM for work automation, using the selection tool to highlight data, and then opening a webpage and inputting the data into a field.

This is done with two scripts, one to take the selected data and open the new tab, and one on the loaded tab to input the data into the field.

the onload script is ran via the "Execute when visiting specified sites", but the script doesn't run unless I've gone into the options and resave the script. if I then refresh the page, the onload script functions properly.

However, closing the tab and opening a new tab with the same page, the script fails to run unless once again, I save the script in options first.

### the selection script:
```
var search = crmAPI.getSelection();
var url = 'REDACTED#%s';
var toOpen = url.replace(/%s/g,search);
var win = window.open(toOpen, '_blank');
```

### the onload script:
```
const str = document.URL;
const slug = str.split('#').pop();
document.getElementById('what').value = slug;
```

As you can see, this just adds "#whateverISelected" to the URL, such as www.google.com#whateverISelected", then on load it takes the URL and enters whatever is after the # into the data field.

The script functions as intended once the script is resaved and will run on the tab in question.

**Comment by SanderRonde** [comment]
I've managed to track the issue down and fixed it in f4c666262c355c41cc72bb7985a0357db5673e02. The fix should be in the next release, which I've just submitted.
