### ISSUE TITLE
[wiki] please give an example how to pass link as an argument for search engine

### ISSUE THREAD

**Issue by ohhai** [SanderRonde/CustomRightClickMenu#57]
What I want to have: open any link (not a text selected) in google cache by right click (using firefox 85).

Already have bookmarked `http://webcache.googleusercontent.com/search?client=firefox-b-d&strip=0&vwsrc=0&q=cache:%s` with keyword `gc`, so I can copy url and use address bar like "ctrl+l, gc, space, ctrl+v, enter".

It might be easier with CRCM, but I can't figure how to pass right-clicked link as an argument. `%s` and `#1` and `%1` seem not the case

**Comment by SanderRonde** [comment]
I've created a [wiki entry here](https://github.com/SanderRonde/CustomRightClickMenu/wiki/Using-a-clicked-link-as-an-argument-for-a-URL). In your case, just replace the `example.com` URL with the one you supplied (of course removing the %s).

I hope this helps, let me know if you need more help.

**Comment by ohhai** [comment]
It works, thank you!
New tab does not open by default because of Firefox popup blocker triggered, but it's not critical.

**Comment by SanderRonde** [comment]
Good to hear! Yeah that shouldn't be a huge issue, you can probably turn that off somewhere.
