### ISSUE TITLE
[wiki]How to add Copy Tab URL

### ISSUE THREAD

**Issue by PeaceByJesus** [SanderRonde/CustomRightClickMenu#58]
I find it hard to believe that  Copy Tab URL is missing in Chrome and  its cousins, whereas in  Firefox that is available via an extension, and which is why I installed yours. But how would i add that option using it?  Otherwise one must open the tab in order to copy the url of a tab. Thanks.

**Comment by SanderRonde** [comment]
I'm not really sure what you mean. Do you mean copying the URL of the current tab? Copying the URL of a tab that is pointed to by some link or copying the URL of some other tab?

**Comment by PeaceByJesus** [comment]
Thanks for getting back to me, and sorry for my own delay, but I mean that when you right click on any tab then the menu includes Copy URL As in  Firefox Quantum (with an extension and  Firefox legacy:  https://live.staticflickr.com/65535/50905585371_a12c31d2b6_z.jpg

**Comment by SanderRonde** [comment]
Ah that should be fairly easy. Just create a new script and paste in the following script:

```js
window.crmAPI.GM.GM_setClipboard(location.href);
```

That's it. Let me know if it works.

**Comment by PeaceByJesus** [comment]
Well, I am not sure if I did it right. There is no entry on right click itself for creating a new script, and via to the toolbar icon  I went to chrome-extension://onnbmgmepodkilcbdodhfepllfmafmlj/html/options.html and clicked on Add Script = My Script Add here and pasted your script and saved it, but there is nothing added to the right click menu. Sorry.

**Comment by SanderRonde** [comment]
Oh I just realized you meant copying the tab URL when right-clicking on the tab itself. Unfortunately that's not possible. The browser APIs that are available to me only restrict me to changing the right-click menu on the page. While this API does seems to be available in Firefox, it's not possible on any other platform and it's a non-standard feature so I can't really implement it.

Also you were correct in going to the options page and adding the script there. That should make the script show up when you right-click on the page, after which you can still copy the URL of that page by clicking on it. But I'm pretty sure that's not the copy feature you're looking for.

**Comment by PeaceByJesus** [comment]
Thanks for getting back to me, but sorry to hear that copying the tab URL when right-clicking on the tab  is not possible. Which is just one more of the wealth of options that I am looking for in a modern browser which we lost after Firefox went Quantum.  

I still use Firefox ESR 59.2 along with other browsers though, even though I must be more and  more selective, but thank God we have so many browsers and tools to make good use of.  And for those as yourself who work to supply them. 

Thanks again. Grace and peace thru Jesus the Lord.

**Comment by SanderRonde** [comment]
Yeah there's some blog post out there describing why all the modding was removed from Firefox Quantum but I can't find it unfortunately. But I can definitely imagine it not being nice from the user's point of view.

You're very welcome. I'll close this issue now.

**Comment by PeaceByJesus** [comment]
You are very understanding, gracious and communicative and an asset to Vivaldi.
