### ISSUE TITLE
Can I add running some local .bat .cmd  command line file or python

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#6]
Can I add running some local .bat .cmd command line file or python?

For example:

When I'm on some Youtube page I right click and run a command line to get the subtitle.

**Comment by SanderRonde** [comment]
I just uploaded the 2.0 version, so it should be out in a few hours. In the option page of that version there is a section called "Launching programs instead of links" that does exactly what you want to do. If you've got the 2.0 version and still can't make it work, feel free to re-open the issue.
