### ISSUE TITLE
CRX_SIGNATURE_VERIFICATION_FAILED - Cant add extension to edge

### ISSUE THREAD

**Issue by marcusobrien** [SanderRonde/CustomRightClickMenu#60]
Hi, 

I try to add the extension to my edge browser on Windows 10 and I get this error in a popup dialog

CRX_SIGNATURE_VERIFICATION_FAILED

I can't leave a review to tell you this on the extension page, as you have to I have the extension installed to leave a review - catch 22.

My MS edge browser is up to date 
Version 96.0.1054.62 (Official build) (64-bit)

**Comment by SanderRonde** [comment]
Thanks for the report, I've managed to reproduce it (seems to affect just everyone downloading from the edge store).

I'm actually not sure what is causing this error but I've submitted a new version to the edge extension store. Hopefully a re-submission will fix it. It should take around 7 business days for the new version to be admitted so I'll give it another try when the new version passes.

**Comment by SanderRonde** [comment]
The re-submission did not work. I've sent a support request to Microsoft and hopefully they'll follow up with a solution.

**Comment by SanderRonde** [comment]
Uploaded a new version and it works again!
