### ISSUE TITLE
An error occurred. The package is invalid:“CRX_SIGNATURE_VERIFICATION_FAILED”

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#62]
I tried many time for installing this extension for Edge browser, but always failed.

`An error occurred. The package is invalid:“CRX_SIGNATURE_VERIFICATION_FAILED”`

https://microsoftedge.microsoft.com/addons/detail/custom-rightclick-menu/fkghdebjaamoikkiapjnobiboijngklh

**Comment by SanderRonde** [comment]
I've sent a support request to microsoft, hopefully they'll know how to fix this issue since it's a bit of a mystery for me. In the meantime I'll close this issue since there's already an outstanding issue for this problem (namely #60). I'll be tracking the problem in that issue.
