### ISSUE TITLE
Can't run the script on chrome-extension:// page.

### ISSUE THREAD

**Issue by pendave** [SanderRonde/CustomRightClickMenu#65]
Hello, I need to run some javascript on pages like some extension's:

chrome-extension://denbgaamihkadbghdceggmchnflmhpmk/result.html

`const btm = document.querySelector('#fullCapture');
btm.click();
const top = document.querySelector('div[commandname="onCaptureRequested"]');
top.click();`

But it's not working, though it works on normal website pages. 

Is it due to secruity reason? Could CustomRightClickMenu bypass the limit? Where to set it up?

**Comment by SanderRonde** [comment]
Yeah this is unfortunately not possible due to security reasons enforced by Chrome itself. AFAIK it's not possible to bypass them.
