### ISSUE TITLE
Is it possible to add items straight to the context menu and not into the submenu?

### ISSUE THREAD

**Issue by bathrobehero** [SanderRonde/CustomRightClickMenu#66]
Hey, so title basically says it all. I'm basically not interested in having to always open the "Custom Menu" and pick what I want from the context menu, rather I'd like to have all my options listed straight when I right click. Can this be done?

**Comment by SanderRonde** [comment]
Nope, unfortunately not. The browser API unfortunately does not allow this.

**Comment by bathrobehero** [comment]
Oh, I see. Thanks for the fast reply!

**Comment by SanderRonde** [comment]
Since I get this question quite often I'll pin it so that others can see it as well :)
