### ISSUE TITLE
Cannot rename main node (Custom Menu) to something else in EDGE (works in Google)

### ISSUE THREAD

**Issue by luggerhouse** [SanderRonde/CustomRightClickMenu#67]
Hi, 
thanks for your tremendous work! It fitted exactly what I needed.

I installed your module on chrome before finding out there was also the same for Edge.

Works great except that I was not able to rename the main node to something else.

How to reproduce:

install module on EDGE 
open options of the module
rename main node from "Custom Menu" to something else ("test" is an example)
focus out the field to apply.
Reload page 

Main node still appears as "Custom Menu" when done in Edge but works in Google.

**Comment by luggerhouse** [comment]
Hi,

Thanks for your reply 😊

This is a minor esthetic issue, it won’t stop me from using the module lol

I just wanted to let you know in case it would matter.

I tried the workaround without success, the console returns an error :

                options.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'upload')
    at t.upload (options.js:160:129071)
    at <anonymous>:1:8

but it doesn’t matter, we mostly use Chrome anyway 😊

Thanks again for your Genius and I will checkout the rest of your repository for sure !

Stefan

De : Sander ***@***.***>
Envoyé le :28 septembre 2022 10:31
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [SanderRonde/CustomRightClickMenu] Cannot rename main node (Custom Menu) to something else in EDGE (works in Google) (Issue #67)


Hmm not really sure what's going wrong there. I'm not really maintaining this project that actively at the moment so I'm probably not going to figure out and fix the bug (which is likely to be extra hard because different platforms and stuff). But I will provide you with a workaround!

On the options page, follow these steps:

  *   Open your developer tools (F12)
  *   Go to the console pane (it's in the top row, click the little >> if you don't see it initially)
  *   Enter this code and press enter: window.app.settings.rootName = 'theNameYouWant';
  *   Enter this code and press enter: window.app.upload(true);

The name should then have updated. Can you let me know if this works?

**Comment by SanderRonde** [comment]
Ah alright, thank you for the kind words!
