### ISSUE TITLE
Manage permissions dialog is not working

### ISSUE THREAD

**Issue by lzl124631x** [SanderRonde/CustomRightClickMenu#68]
The toggles in this "manage" dialog is not working. The setting is lost after closing this dialog.

BTW, for testing, I added `console.log` and `alert` and they didn't work at all. Openning the background.html shows 
```
message: "Could not establish connection. Receiving end does not exist."
```

Is this extension still working?

**Comment by SanderRonde** [comment]
It sounds like the background.js file crashed. Could you go to the chrome://extensions page, then to the extension's details and open the background page? There should be an error listed somewhere.

**Comment by SanderRonde** [comment]
Closing for now since there has been no response in a (long) while.
