### ISSUE TITLE
Is it possible the use the current tab url in the link settings?

### ISSUE THREAD

**Issue by jakezz** [SanderRonde/CustomRightClickMenu#75]
Are there any special variables accessible in the link settings? For example can I make a menu link that points to:

https://web.archive.org/web/20230000000000*/[current_tab_url]

Or when right clicking on a link on a page could I make a menu link point to:

https://web.archive.org/web/20230000000000*/[hyperlink_url]

If it is possible to do both, is there a way to make both work under 1 menu link? :q Edit: nvm this one I see the content type stuff now.

**Comment by SanderRonde** [comment]
Yep certainly, when turning a menu item into a script (or just clicking "add script") you can add a bit of custom javascript that can do pretty much whatever you want. The code you'll need is probably:

And your second request:
```js
window.open(
  `https://web.archive.org/web/20230000000000*/${encodeURIComponent(
    window.crmAPI.contextData?.target?.href ?? location.href
  )}`,
  "_blank"
);
```

That will basically take the link that is attached to whatever you clicked on (if a link), and if there is no link (aka you clicked on the page itself) it'll use the current page URL. Does that help?

**Comment by SanderRonde** [comment]
Closing for now since there hasn't been a response in a while.
