### ISSUE TITLE
add text to the context menu that when you click on the text it adds it to the form text box

### ISSUE THREAD

**Issue by knowltonGitHub** [SanderRonde/CustomRightClickMenu#76]
I want to be able to paste the value of an item in the context menu into a field on a form.

So say I am filling-out data on a form.  I right-click on a field labeled "Street Address" and the context menu opens.  One of the items I have added (using your extension) is my address of "123 Anywhere Street" let's say.  I go and click on the text "123 Anywhere Street" from the context menu.  That text is now "pasted" into the "Street Address" field for the form I am filling-out.

Possible?

I right click on the Street Address field on the form:

![right click to choose text to paste](https://user-images.githubusercontent.com/26986675/227731067-43459e80-689b-4882-b96c-503e7a201063.png)

After selecting the text in the context menu, it is pasted into the Street Address field:

![after clicking on the context menu item](https://user-images.githubusercontent.com/26986675/227731063-baf90ed6-5123-446a-9841-604f1a990f75.png)

**Comment by SanderRonde** [comment]
Yep that's pretty easy, just put the following code into a script node:
```
let target = crmAPI.contextData.target;
if (target.tagName.toLowerCase() !== 'input') {
    target = target.querySelector('input');
}
target.value = '123 Anywhere Street';
```

Note that this will only work if you're right-clicking an input field, if you right-click on another node on the page and do this it'll do nothing (obviously). It might be that it doesn't work on some pages depending on how they've implemented their input elements. For example sometimes they wrap a bunch of divs around them to make them pretty. Essentially what this code does is:
- Get the context data - aka context of your click
- Get the current target - aka the element you right-clicked on
- If it's not an input element, find any child element that is an input element
- Paste the text

If you find it not working on some websites, the trick is basically resolving "the element you right-clicked on". You might have to fix it on those websites to make the "find any child that is an input element" step better, but I'll leave that as a challenge to the user ;)

**Comment by knowltonGitHub** [comment]
A "Script Node" is something CRM supports?

This is my first day using your extension.

Is there a step by step or tutorial for how to do this?  I need it spelled-out for me.  : )

**Comment by SanderRonde** [comment]
See the first 4 steps of this tutorial: https://github.com/SanderRonde/CustomRightClickMenu/wiki/Adding-a-search-engine

**Comment by knowltonGitHub** [comment]
It worked!!!!!!

Thank you SO MUCH for writing this extension.  I am a beginner chrome extension author and I found your extension while trying to create a new extension that does what (I laterlearned) your extension already does

**Comment by SanderRonde** [comment]
Glad to hear! I'll close this issue for now since it sounds like it's been resolved
