### ISSUE TITLE
Get text from the CRM item clicked

### ISSUE THREAD

**Issue by knowltonGitHub** [SanderRonde/CustomRightClickMenu#77]
When I click on an item that I added to the CRM, how do I get the value of the self same item?

Using a script for an item I am clicking on ...  I want to make use of the text "123 Anywhere Street" as depicted below:

![get value of selected menu item](https://user-images.githubusercontent.com/26986675/227803318-bad64cf6-d05d-415c-bfe6-0e67170fb1ed.png)

```
let target = crmAPI.contextData.target;
var newText = crmAPI.getClickInfo().selectionText;

if (target.tagName.toLowerCase() !== 'input') {
    target = target.querySelector('input');
}

target.value = newText ;
```

I keep getting 'undefined'

(if this looks familiar, I asked almost the [same question](https://github.com/SanderRonde/CustomRightClickMenu/issues/76) just the other day)

**Comment by knowltonGitHub** [comment]
is 

crmAPI.getClickInfo().selectionText;

the correct way to get the value of the clicked menu item?

**Comment by SanderRonde** [comment]
No that will get the selected text on the page ([see docs](https://sanderronde.github.io/CustomRightClickMenu/documentation/interfaces/crm.crmapi.clickdata.html#selectiontext)), what you're looking for instead is [getNode](https://sanderronde.github.io/CustomRightClickMenu/documentation/classes/crm.crmapi.instance.html#getnode-1).[name](https://sanderronde.github.io/CustomRightClickMenu/documentation/interfaces/crm.scriptnode.html#name)

**Comment by knowltonGitHub** [comment]
Yep!  Thank you!

My corrected JavaScript:

```
let target = crmAPI.contextData.target;
var newText = crmAPI.getNode().name;

//console.log(newText);

if (target.tagName.toLowerCase() !== 'input') {
    target = target.querySelector('input');
}

target.value = newText;
```


Is there a way to CENTRALIZE the various clicks?

What I mean is ... I want to use the JavaScript above for ALL of the items in the custom CRM menu:

"123 Anywhere Street"
"Thomas"
"Knowlton"
"City, State, Zip"

etc.

all would have to use the SAME JavaScript snippet above.

I want to send the various menu item text messages all to the SAME snippet --- but I only want to write the snippet ONCE, instead of having to paste this snippet over and over for each item (as I would have to do currently)

I hope this explanation makes sense.  Kind of like this


function PasteCustomValueIntoField(somevalue){
let target = crmAPI.contextData.target;
var newText = somevalue;

console.log(newText);

if (target.tagName.toLowerCase() !== 'input') {
    target = target.querySelector('input');
}

target.value = newText;
}


PasteCustomValueIntoField(crmAPI.getNode().name);

which for each item would equate to these calls:

PasteCustomValueIntoField("123 Anywhere Street");
PasteCustomValueIntoField("Thomas");
PasteCustomValueIntoField("Knowlton");
PasteCustomValueIntoField("City, State, Zip");

**Comment by SanderRonde** [comment]
Yes, you can use the `libraries` feature. You could enter your `PasteCustomValueIntoField` code as a library, use that library for each of the nodes and then all you'd have to do is call it in the node. If you make the value rely on the name you won't even have to pass the text (although I'd do that explicitly anyways). See the libraries tab on the script configuration page.

**Comment by knowltonGitHub** [comment]
Sorry, I do not see the libraries feature.

**Comment by SanderRonde** [comment]
See the image for where to find the libraries feature.

What does happen when you click the item in the CRM menu? Does anything show up in the console at all? Any errors?

![image](https://user-images.githubusercontent.com/5385012/228336152-638f37d1-b162-4bb3-87b0-ff690b81cd5d.png)

**Comment by knowltonGitHub** [comment]
As far as I can tell, no errors.  Here is a screenshot, and the console text as well:

![2023-03-28 12_47_13-Options](https://user-images.githubusercontent.com/26986675/228338012-5a6632d0-6553-43de-81c5-7bbff6e69848.png)


CONSOLE TEXT:

DevTools failed to load source map: Could not load content for https://localhost:49506/8ee4ea609a6346c4cf34c2b621ac79ba.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
8ee4ea609a6346c4cf34c2b621ac79ba.js:2 [Violation] 'setTimeout' handler took 88ms
8ee4ea609a6346c4cf34c2b621ac79ba.js:2          GET https://localhost:49506/storage/loggerQueue 404 (Not Found)
i @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
value @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
value @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
value @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
value @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
value @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
value @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
e @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
n @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
n @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
n @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
n @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
(anonymous) @ 8ee4ea609a6346c4cf34c2b621ac79ba.js:2
[Violation] 'setTimeout' handler took 134ms
[Violation] Forced reflow while executing JavaScript took 93ms

**Comment by SanderRonde** [comment]
You'll want to check the console output on the page where you actually run the script. So if you go the form in your [original question](https://github.com/SanderRonde/CustomRightClickMenu/issues/76) and click the right-click menu item. (important: open the console beforehand clicking or it might miss some details)

**Comment by knowltonGitHub** [comment]
What I got:

![2023-03-28 13_00_03-Window](https://user-images.githubusercontent.com/26986675/228341119-97459af1-451d-450d-977e-76edbbad8e80.png)



and this when I RIGHT-CLICKED the menu item:

![2023-03-28 12_58_23-Address form _ U S  Web Design System (USWDS)](https://user-images.githubusercontent.com/26986675/228341233-01e8bbf4-491c-4d6d-bd3e-fb5f56bbad6a.png)

**Comment by knowltonGitHub** [comment]
Either way, the text "Information Technology" got pasted into the field...which was not what I expected.  I expected the field to be blank after I chose the right-click menu item.

**Comment by knowltonGitHub** [comment]
Are you allowed to use either SCRIPT or LIBRARY for ALL of the menu items, but not decide individually for each item?  For some items I may want to run a SCRIPT.  For other items I may want to share the central LIBRARY.

**Comment by SanderRonde** [comment]
Ah yeah regarding the first error you'd want to use `var target` instead of `let target`, then it works. Also I'm not really sure what right-clicking the menu items does.

Why would the field be blank? On-click you run a script that sets the content of the field right (see the source code in your first image). What should it do?

You can choose individually for every item, and you don't even have to choose between script and library. You can use a script in combination with a library (that's the whole idea, you can load something like jquery or underscore and make use of it in your script). You can even enable or disable the library on a per-script-node basis by clicking it. The checkmark indicates whether it's used.

**Comment by knowltonGitHub** [comment]
I swear - it is like changing whatever I pick to be THAT for every item.
If I pick a LIBRARY function...all the menu items become LIBRARY functions,
not just the one I picked it for.  If I change one of them to just use a
MAIN script...they all change over to that.

I'll have to see if I can find a way to record what I am seeing.  It's
quite odd, given how you have described the way it SHOULD work.

Tom

**Comment by knowltonGitHub** [comment]
See if this video makes any sense:

https://share.vidyard.com/watch/xeq682gFrbE9WwKFmeJoSq?

**Comment by knowltonGitHub** [comment]
This link to a recording below is a little better.

Watch as I move between the first and the second menu items.  They are both *just* SCRIPTS.  Then, I change the first script to a LIBRARY function and save my changes.  Then notice that when I go to the second menu item...it has also now changed to a LIBRARY function, _whereas it used to be a SCRIPT!_



https://share.vidyard.com/watch/FCkgg1Ty2q27AGVQqwzRLW?

**Comment by knowltonGitHub** [comment]
I tried reloading the page in between to reset it and it still does what my
screen recording shows.

For now my workaround is to do as you suggest:  paste the same code in for
every menu item.  That does work, for sure.  It is a shame I cannot get the
library feature to work for me.

I don't know if it is a bug or not.  It seems like one to me.  I am happy
to help investigate this further, but I am not sure if mere console.log
type debugging will be sufficient.
