### ISSUE TITLE
chromeHolder.chrome.runtime.getURl is not a function

### ISSUE THREAD

**Issue by bumaociyuan** [SanderRonde/CustomRightClickMenu#8]
Hi @SanderRonde 
Thank you for the plugin.

I got the error ```chromeHolder.chrome.runtime.getURl is not a function``` 

https://github.com/SanderRonde/CustomRightClickMenu/blob/fef5710a6edf7c9a197df76a950be662461641c3/app/js/crmapi.js#L3269

Maybe the `getURl`'s `l` should be a  capital

**Comment by SanderRonde** [comment]
Hey thanks for opening the issue, that was indeed the source of the problem, the fixed version should be live in a couple of hours
