### ISSUE TITLE
image right click

### ISSUE THREAD

**Issue by s177oke77** [SanderRonde/CustomRightClickMenu#80]
I am trying to pass along an image from a webpage in chrome to print directly with a batch script that I have written. I am not sure if there is a way of doing this without downloading the image first. My batch script prints the image just fine when downloaded. I am unsure how to pass the parameter of the images location to my batch file. So far this is what I have but my batch requires a parameter: var wshShell = new ActiveXObject("WScript.Shell");
wshShell.Run("C:\Users\XXXX\Desktop\PrintImage.bat"); 

the batch file has:
@echo off
rundll32    shimgvw.dll    ImageView_PrintTo /pt  %1  Printer1

**Comment by SanderRonde** [comment]
Looks like it requires the path to a local file indeed so you'll have to download it and then pass the path. You can download the file using a combination of thr [crmAPI.browser](https://sanderronde.github.io/CustomRightClickMenu/documentation/classes/crm.crmapi.instance.html#browser) and the [chrome.downloads api](https://developer.chrome.com/docs/extensions/reference/downloads/#method-download) to download the file. You should be able to get the path then and pass it on to your batch script.

**Comment by s177oke77** [comment]
is there no way to print an image without first downloading it

**Comment by s177oke77** [comment]
Thank you for your help!
