### ISSUE TITLE
Conflict with Tampermonkey

### ISSUE THREAD

**Issue by ltanh1906** [SanderRonde/CustomRightClickMenu#83]
Everytime i install new scripts the tab of this extension show up instead of tamper monkey. Is there any method to set tampermonkey as default install scripts ?

**Comment by SanderRonde** [comment]
Unfortunately not. The extension disables the install behavior automatically when it detects that tampermonkey/greasemonkey is installed (using the extension IDs listed [here](https://github.com/SanderRonde/CustomRightClickMenu/blob/f32c11b0c9840ebc6ccf0ea365a7027500c272e5/app/js/background/global.ts#L608)), but it could be that those extension IDs are now wrong...

Unfortunately I can't really update the extension anymore (see [wiki](https://github.com/SanderRonde/CustomRightClickMenu/wiki/Why-the-extension-isn't-being-updated-(often)-any-more)) so I'd recommend temporarily disabling/enabling the extension before installing a script as the best solution.
